version: '3.1'

services:
  db:
    image: mysql:5.6
    volumes:
      - "./.data/db:/var/lib/mysql"
      # Place mysql dump in mysql folder for automatic import
      - "./mysql:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mydatabase
  wordpress:
    depends_on:
      - db
    build:
      context: "./docker/wordpress"
    volumes:
      - "./cms:/var/www/html"
      - "./fabricator:/var/www/fabricator"
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: mydatabase
      WORDPRESS_TABLE_PREFIX: wp_
  mail:
    image: mailhog/mailhog:latest
    depends_on:
      - wordpress
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
